INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (1, 'Data Systems Design', 3, 'Stratos Idreos')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (2, 'Algorithms for Social Data', 4.5, 'Yaron Singer')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (3, 'Programming Languages and Security', 2.5, 'Stephen Chong')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (4, 'Networking at Scale', 3.5, 'Minlan Yu')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (5, 'Statistical Reinforcement Learning', 4, 'Susan Murphy')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (6, 'Tiny Machine Learning', 5, 'Vijay Janapa Reddi')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (7, 'Privacy and Technology', 3, 'James Waldo')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (8, 'Introduction to Distributed Computing', 3, 'James Waldo')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (9, 'Computer Vision', 3, 'Todd Zickler')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (10, 'Computer Graphics', 2, 'Steven Gortler')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (11, 'Discrete Optimization', 6, 'Hanspeter Pfister')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (12, 'Analysis of Algorithms', 3, 'John Doe')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (13, 'Object Oriented Programming', 3, 'David Finch')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (14, 'Data Structures', 4.5, 'Stan Smith')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (15, 'Microprocessors', 3, 'Jack London')
INSERT INTO COURSE (ID, TITLE, CREDIT, INSTRUCTOR) VALUES (16, 'Real Time System Design', 3, 'Harry Lewis')