spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mbiberci/university-app.git
          force-pull: true
          search-paths: config-data

server:
  port: 8888
